###Index Employee
GET http://localhost:3000/employees.json

###Show Employee
GET http://localhost:3000/employees/1.json

###Create Employee
POST http://localhost:3000/employees.json
Content-Type: application/json

{
  "first_name": "Amanda",
  "last_name": "Shakespeare",
  "email": "William@example.com",
  "phone": "111-1111",
  "job_title": "Driver",
  "department_id": 1
}

###Update Employee
PATCH http://localhost:3000/employees/3.json
Content-Type: application/json

{
  "job_title": "Reader",
  "admin": true
} 

###Destroy Employee
DELETE http://localhost:3000/employees/8.json

